In [1]:
import numpy as np
import random
import copy
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

In [2]:
KSI = np.zeros((5, 25))
KSI[0,:2] = 1 
KSI[1,2:8] = 1 
KSI[2,8:19] = 1 
KSI[3,19:23] = 1 
KSI[4,23:] = 1 
KSI

array([[1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 1., 1.]])

In [3]:
Y = np.array([83, 85, 84, 85, 85, 86, 86, 87, 86, 87, 87, 87, 88, 88, 88, 88, 88, 89, 90, 89, 90, 90, 91, 90, 92])

In [4]:
model = LinearRegression(fit_intercept=False)
model.fit(KSI.T,Y.T)

LinearRegression(fit_intercept=False)

In [5]:
b = model.coef_
b

array([84.        , 85.5       , 87.81818182, 90.        , 91.        ])

In [6]:
F = KSI @ KSI.T    # матрица Фишера
print(F)
F_1 = np.linalg.inv(F)    # обратная матрица Фишера
fii = np.array([0.,0.,0.,0.,0.])
for i in range(5):    
    fii[i] = F_1[i,i] 
fii    # диагональные эл-ты м Фишера

[[ 2.  0.  0.  0.  0.]
 [ 0.  6.  0.  0.  0.]
 [ 0.  0. 11.  0.  0.]
 [ 0.  0.  0.  4.  0.]
 [ 0.  0.  0.  0.  2.]]


array([0.5       , 0.16666667, 0.09090909, 0.25      , 0.5       ])

In [7]:
n = 25
r_sq = model.score(KSI.T, Y.T)    # коэф детерминации
print("R_sq = ", r_sq)
TSS = 0     # дисперсия откликов
for i in range(n):
    TSS += (Y[i] - Y.mean())**2

print("TSS = ",TSS)

RSS = (1 - r_sq) * TSS  # остаточная сумма квадратов
print("RSS = ", RSS)

# проверка значимости коэф-тов
delta = np.array([0.,0.,0.,0.,0.])
for i in range(5):
    delta[i] = b[i] * (n-5)**0.5 / ((RSS * fii[i] ) ** 0.5)

delta    



R_sq =  0.8106060606060606
TSS =  122.16
RSS =  23.136363636363644


array([110.44898546, 194.719384  , 270.79973244, 167.35548556,
       119.65306758])

H0 отвергаем, значит все коэф-ты значимы

In [8]:
delta_regressii = (r_sq / (1-r_sq) )* ((n-5) / (5-1))
delta_regressii

21.39999999999999

критическое значение F(5, 19) = 2.18 - > регрессия значима

## b)

In [9]:
delta = np.zeros((5, 5))
for i in range(5):
    for j in range(i+1, 5):
        delta[i,j] = (b[j] - b[i])/(RSS*(fii[i] + fii[j]))**0.5 *(20)**0.5
        
delta

array([[0.        , 1.70806477, 4.61810408, 6.44151564, 6.50826888],
       [0.        , 0.        , 4.24680627, 6.48165008, 6.26290416],
       [0.        , 0.        , 0.        , 3.47429517, 3.84842007],
       [0.        , 0.        , 0.        , 0.        , 1.07358594],
       [0.        , 0.        , 0.        , 0.        , 0.        ]])

d = 2.1 - критическая точка t(20)

значит 1-2, 4-5 одинаковые группы